version: "2.2"
services:
    spark-master:
      image: bde2020/spark-master:2.4.5-hadoop2.7
      container_name: spark-master
      ports:
        - 6066:6066
        - 7077:7077
        - 8080:8080
      expose:
        - 7001
        - 7002
        - 7003
        - 7004
        - 7005
        - 7006
        - 7077
        - 6066
        - 4040
        - 9000
      environment:
        - INIT_DAEMON_STEP=setup_spark
        - "constraint:node==spark-master"
      cpus: 0.5
      mem_limit: 1024M
      hostname: "spark-master"
      networks: 
                - internal
    spark-worker-1:
      image: bde2020/spark-worker:2.4.5-hadoop2.7
      container_name: spark-worker-1
      depends_on:
        - spark-master
      expose:
          - 7012
          - 7013
          - 7014
          - 7015
          - 7016
          - 8881
          - 8081
          - 9001
          - 9002
      ports:
          - 8081:8081
      environment:
        - "SPARK_MASTER=spark://spark-master:7077"
        - "constraint:node==spark-worker-1"
        - "SPARK_WORKER_PORT = 9001"
      cpus: 0.25
      mem_limit: 1024M
      hostname: "spark-worker-1"
      networks: 
                - internal
      links:
        - spark-master:spark-master
networks:
    internal:
        driver: bridge

